### ISSUE TITLE
Creation of cluster is failing

### ISSUE THREAD

**Issue by bitno** [coneda/kor_cluster#4]
Starting point: Following your steps from https://github.com/coneda/kor_cluster/blob/master/README.md
Installation fails at: $ CLUSTER_PORT=443 ./cluster.sh create /var/my_kor_cluster
Error message: $ ./cluster.sh: line 30: pwgen: command not found

In line 30 of https://github.com/coneda/kor_cluster/blob/master/cluster.sh: CLUSTER_NAME=${2-`pwgen 6 1`}

Any idea what I'm missing?

**Comment by moritzschepp** [comment]
... right! This is more a documentation issue: kor_cluster requires pwgen which you have to install before using it. I'll add this to the readme.
